package portfolio;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.io.*;
import java.util.Vector;
import org.jaxen.JaxenException;
import org.jaxen.XPath;
import org.jaxen.jdom.JDOMXPath;
import org.jdom.*;
import languages.xml.*;

public class GeneratedPlans {

	//This class is used for storing the plans generated by the planners
	private List<List<Element>> Plans;
	//Plans is structed in 2 level. The outer list represents the planners, the inner the training instances
	//e.g. Plans.at(1).at(2) indicates the plan generated by the 2nd planner for the 3rd problem.
	
	public GeneratedPlans(){
		Plans = new ArrayList<List<Element>>();
	}
	
	public void save_plan(int planner, int problem, Element xmlPlan){
		if(Plans.size() <= planner)
			Plans.add(new ArrayList<Element>());
		List<Element> single= Plans.get(planner);
		single.add(xmlPlan);
		Plans.set(planner, single);
		return;
	}
	
	public void analyze_plans(){
		//It cycles on the XMLs generated by solve_problems and extract the required information
		//(plan length, duration, CPU time, ... ). Again, such results must be saved somehwere; I believe
		//that a Planner class should be added.
		return;
	}
	
	public void print_all_plans(){
		for(int i=0; i < Plans.size(); i++)
			for(int j=0; j < Plans.get(i).size(); j++){
				XMLUtilities.printXML(Plans.get(i).get(j));
			}
	}
}
